### ISSUE TITLE
readme.md needs to be updated?

### ISSUE THREAD

**Issue by jacobhurst** [antigenomics/vdjviz#39]
Hi,
I download via git clone but I can see no sign of the bin directory that is referenced in the README as a result, I can't install!
best wishes
Jake

**Comment by bvdmitri** [comment]
Hello, git clone just download the source code, there is no bin/ directory.
You need to download latest binary release from this page: https://github.com/antigenomics/vdjviz/releases

Please feel free to ask other questions with installation process.

Best wishes,
Dmitri.
